apiVersion: apps/v1
kind: Deployment
metadata:
  name: lunix07-app-test-flask-deployed-deployment
  labels:
    app: lunix07-app-test-flask-deployed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lunix07-app-test-flask-deployed
  template:
    metadata:
      labels:
        app: lunix07-app-test-flask-deployed
    spec:
      containers:
        - name: lunix07-app-test-flask-deployed-container
          image: lunix007/lunix07-app-test-flask-deployed:59901e6d57a6b6cff12af7daa1a9972e26e30d1f
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            # Add environment variables here if needed
            - name: ENV
              value: "production"
